version: "3.9"

services:
  backend: &backend
    container_name: django-base
    hostname: django-base
    restart: always
    build: .
    volumes:
      - .:/app
    env_file:
      - .env
    command: >
      sh -c " python manage.py collectstatic  --no-input --clear && python manage.py migrate && gunicorn --reload --access-logfile - --workers 3 --bind 0.0.0.0:8000 core.wsgi:application"
    #      sh -c " tail -f /dev/null"
    #      sh -c "python manage.py makemigrations --merge"
    networks:
      - default

  celery-worker:
    <<: *backend
    container_name: celery-worker
    command: >
      sh -c "celery -A core worker -l info"

    networks:
      - default

  celery-beat:
    <<: *backend
    container_name: celery-beat
    command: >
      sh -c "celery -A core beat -l info"

#    networks:
#      - default

networks:
  default:
    external: true
    name: "app"
